version: 2.1

orbs:
  python: circleci/python@0.2.1
  heroku: circleci/heroku@0.0.10

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python ./tests/app_unit_tests.py
          name: app.py Tests
      - run:
          command: python ./tests/forward_geocoding_unit_test.py
          name: forward_geocoding_unit_test.py Tests
      - run:
          command: python ./tests/hourly_weather_unit_test.py
          name: hourly_weather_unit_test.py Tests
      - run:
          command: python ./tests/tweets_unit_tests.py
          name: tweets_unit_test.py Tests
      - run:
          command: python ./tests/news_unit_tests.py
          name: news_unit_tests.py Tests
      - run:
          command: python ./tests/national_parks_unit_test.py
          name: national_parks_unit_test.py Tests
  heroku-deploy:
    executor: python/default
    steps:
      - checkout
      - run:
          command: git push --force https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
      

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build-and-test
      - heroku-deploy: # Maybe use the pre-configured job, heroku/deploy-via-git
          requires:
            - build-and-test
          filters:
            branches:
              only: master